package com.shortlinkx.service;
import com.shortlinkx.dto.*;import com.shortlinkx.entity.ShortUrl;import com.shortlinkx.repository.ShortUrlRepository;import org.springframework.beans.factory.annotation.Value;import org.springframework.dao.DataIntegrityViolationException;import org.springframework.data.redis.core.StringRedisTemplate;import org.springframework.stereotype.Service;import java.time.Duration;import java.time.LocalDateTime;
@Service public class ShortUrlService{
 private final ShortUrlRepository repo;private final StringRedisTemplate redis;private final String base;
 public ShortUrlService(ShortUrlRepository repo,StringRedisTemplate redis,@Value("${shortlinkx.base-url}")String base){this.repo=repo;this.redis=redis;this.base=base;}
 public CreateUrlResponse create(CreateUrlRequest r){String code=r.customAlias()==null||r.customAlias().isBlank()?generate():r.customAlias().trim();if(repo.findByShortCode(code).isPresent())throw new IllegalArgumentException("Short code already exists: "+code);ShortUrl u=new ShortUrl(r.longUrl(),code,r.expiresAt());try{repo.save(u);}catch(DataIntegrityViolationException e){throw new IllegalArgumentException("Short code collision. Please retry.");}cache(u);return new CreateUrlResponse(code,base+code,u.getLongUrl(),u.getExpiresAt());}
 public ShortUrl resolve(String code){String cached=redis.opsForValue().get("url:"+code);if(cached!=null){String[] p=cached.split("\\|",-1);LocalDateTime exp=p[2].isBlank()?null:LocalDateTime.parse(p[2]);if(exp!=null&&!exp.isAfter(LocalDateTime.now())){redis.delete("url:"+code);throw new IllegalArgumentException("Short URL has expired.");}return new ShortUrl(p[0],p[1],exp);}ShortUrl u=repo.findByShortCode(code).orElseThrow(()->new IllegalArgumentException("Short URL not found."));if(u.getExpiresAt()!=null&&!u.getExpiresAt().isAfter(LocalDateTime.now()))throw new IllegalArgumentException("Short URL has expired.");cache(u);return u;}
 private String generate(){String c=Base62.encode(Math.abs(System.nanoTime()));while(repo.findByShortCode(c).isPresent())c=Base62.encode(Math.abs(System.nanoTime()));return c;}
 private void cache(ShortUrl u){String v=u.getLongUrl()+"|"+u.getShortCode()+"|"+(u.getExpiresAt()==null?"":u.getExpiresAt());Duration ttl=u.getExpiresAt()==null?Duration.ofHours(24):Duration.ofSeconds(Math.max(1,Duration.between(LocalDateTime.now(),u.getExpiresAt()).getSeconds()));redis.opsForValue().set("url:"+u.getShortCode(),v,ttl);}
}
